Feature/forget password
mensapc/vrep-elementary-back pull request #117
Opened 2024-03-01 16:05 UTC by mr-chidex

forgot and update password feature API added for staff and admin

2024-03-02 00:26 UTC, stawuah requested changes

2024-03-02 00:26 UTC, stawuah commented on utils/utils.mailer.js
> +const resend = new Resend("re_GkEMskU4_76tPbmzYM6LZoZzQh9s56m9m");
@mr-chidex  this api key for `resend` should be in the `process.env.RESEND_API_KEY`

2024-03-02 00:26 UTC, stawuah commented on utils/utils.mailer.js
> +const sendMal = async ({ subject, to, htmlText }) => {
a minor typo in the codebase by renaming the function `sendMal`  to `sendMail`. The function is responsible for sending emails, and renaming it to `sendMail`  improves code clarity and adheres to standard naming conventions.

2024-03-02 00:26 UTC, stawuah commented on yarn.lock
I'm proposing to address the presence of both `yarn.lock ` and `package-lock.json` files in the project directory. Having both lock files can lead to confusion and potential inconsistencies in dependency resolution, especially considering that they are used by different package managers, `Yarn`  and `npm`, respectively. Simplify dependency management by using a single lock file


### Reason to address presence of both `yarn.lock ` and `package-lock.json`


- Dependency Resolution: Depending on which package manager is used during installation (yarn or npm), one lock file might take precedence over the other. This could lead to unexpected behavior and difficulties in reproducing a consistent development environment.

- Confusion and Inconsistency: Having both lock files can lead to confusion among developers working on the project, especially if they're accustomed to using one package manager over the other. It may also result in inconsistencies in dependency resolution and package versions.

2024-03-02 11:07 UTC, mr-chidex commented
@stawuah updated. Please review.
Also, I don't have write access to the postman.

2024-03-02 16:15 UTC, stawuah approved these changes

2024-03-02 16:17 UTC, stawuah commented
@mr-chidex  , @abetoluwani  will grant you access to that soon

2024-03-05 08:11 UTC, stawuah approved these changes

2024-03-05 08:13 UTC, stawuah commented
@RWUBAKWANAYO  kindly have a last  review and merge

2024-03-05 08:25 UTC, RWUBAKWANAYO commented
@stawuah and @mr-chidex do you think that it's a great idea to generate a temporary password for user and ask user to change it later or we can just give user magic link to change Password?

2024-03-07 21:43 UTC, stawuah commented
> @stawuah and @mr-chidex do you think that it's a great idea to generate a temporary password for user and ask user to change it later or we can just give user magic link to change Password?

Yes i suggest we merge and have the magic link implemented too

2024-04-21 14:26 UTC, closed without merging