Feat/core entities
mensapc/vrep-elementary-back pull request #64
Opened 2023-08-24 20:02 UTC by stawuah

A  fresh pair of eyes is always valuable to catch anything I might have missed. hehe

2023-08-24 20:28 UTC, RWUBAKWANAYO requested changes

2023-08-24 20:28 UTC, RWUBAKWANAYO commented on controllers/student.controller.js
> +                    regNumber = generateRegNumber()
Please validate regNumber before we register it to the collection

2023-08-25 11:10 UTC, RWUBAKWANAYO requested changes

2023-08-25 11:10 UTC, RWUBAKWANAYO commented on controllers/staff.controllers.js
> +            console.error(`Error retrieving all students `, error);
Please change this error message

2023-08-25 11:10 UTC, RWUBAKWANAYO commented on routes/staff.routes.js
> +router.delete('/no/staff', validateToken, authorize(['deleteStaff']), staffController.deleteStaffById);
How are we going to interact with these routes without passing Ids?

2023-08-25 11:10 UTC, RWUBAKWANAYO commented on routes/staff.routes.js
> +router.get('/staff/students', validateToken, authorize(['readStudents']), staffController.findAllStaff);
We arleady created this route inside `students.authroutes.js`

2023-09-07 16:57 UTC, RWUBAKWANAYO reviewed
Please change the name of `routes/calss.route.js` file to `routes/class.route.js`

2023-09-07 17:04 UTC, RWUBAKWANAYO approved these changes

2023-09-09 14:14 UTC, stawuah commented on routes/staff.routes.js
> +router.get('/staff/students', validateToken, authorize(['readStudents']), staffController.findAllStaff);
fixed,

2023-09-09 14:14 UTC, stawuah commented on routes/staff.routes.js
> +router.delete('/no/staff', validateToken, authorize(['deleteStaff']), staffController.deleteStaffById);
Fixed 
```suggestion
router.delete('/no/staff/:staff_id', validateToken, authorize(['deleteStaff']), staffController.deleteStaffById);
```

2023-09-09 14:14 UTC, stawuah commented on routes/staff.routes.js
> +router.get('/staff/students', validateToken, authorize(['readStudents']), staffController.findAllStaff);
```suggestion
router.get('/all/staff', validateToken, authorize(['readStaff']), staffController.findAllStaff);
```

2023-09-09 14:14 UTC, stawuah commented on controllers/student.controller.js
> +                    regNumber = generateRegNumber()
Fixed 
```suggestion
                    regNumber = generateRegNumber() 
```

2023-09-09 14:14 UTC, stawuah commented on controllers/student.controller.js
> +                    regNumber = generateRegNumber()
Registration Validation fixed , no duplicate of reg_numbers and an extra validation to verify 11 digit reg_number before registration and these implementation were done in the model and the ./utils/utils.registrationNumber.js

2023-09-09 14:14 UTC, stawuah commented on controllers/staff.controllers.js
> +            console.error(`Error retrieving all students `, error);
Error message fixed

2023-09-09 14:27 UTC, stawuah reviewed
changes done

2023-09-10 16:07 UTC, stawuah reviewed
fixed

2023-09-10 16:44 UTC, stawuah reviewed
Looks good to me  , @RWUBAKWANAYO

2023-09-29 22:16 UTC, merged